% import CryoGrid modules
addpath('modules/cryoGridTechnical/')
addpath('modules/cryoGridInitialize/')
addpath('modules/cryoGridSEB/')
addpath('modules/cryoGridSoil/')
addpath('modules/cryoGridSnow/')
addpath('modules/cryoGridInfiltrationUnfrozenSoil')
addpath('modules/cryoGridExcessIceInfiltration')
addpath('modules/cryoGridLateral')
addpath('modules/cryoGridTopology')
addpath('modules/cryoGridVisualization')
