function [dE_dt_cond GRID]= heatConductionIceCover(dE_dt_cond, T, k_eff, k_temp, GRID) 

GRID.lake.ice.dE_dt_cond_residual=0;
if ~isempty(GRID.lake.ice.cT_domain_ub) && ~isempty(GRID.lake.water.cT_domain_ub)
    dE_dt_cond_save = dE_dt_cond(GRID.lake.ice.cT_domain_lb) + dE_dt_cond(GRID.lake.ice.cT_domain_lb+1);
    
    if sum(GRID.lake.ice.cT_domain)<2
        
        dE_dt_cond(GRID.lake.ice.cT_domain_lb) = k_temp(GRID.lake.ice.K_domain_lb) .* (0-T(GRID.lake.ice.cT_domain_lb)) ...
            ./ GRID.general.K_delta(GRID.lake.ice.K_domain_lb)./2;
    else
        
        dE_dt_cond(GRID.lake.ice.cT_domain_lb) = k_temp(GRID.lake.ice.K_domain_lb) .* (0-T(GRID.lake.ice.cT_domain_lb)) ...
            ./ GRID.general.K_delta(GRID.lake.ice.K_domain_lb)./2 ...
            - ...
            k_eff(GRID.lake.ice.cT_domain_ub-1) .* (T(GRID.lake.ice.cT_domain_lb)-T(GRID.lake.ice.cT_domain_ub-1)) ...
            ./ GRID.general.cT_delta(GRID.lake.ice.cT_domain_ub-1);
    end
    
    dE_dt_cond(GRID.lake.ice.cT_domain_lb+1) = k_eff(GRID.lake.ice.cT_domain_lb+2).*(T(GRID.lake.ice.cT_domain_lb+2)-T(GRID.lake.ice.cT_domain_lb+1)) ...
        ./ GRID.general.cT_delta(GRID.lake.ice.cT_domain_lb+2) ...
        - ...
        k_temp(GRID.lake.ice.K_domain_lb+1) .* (T(GRID.lake.ice.cT_domain_lb+1)-0) ...
        ./  GRID.general.K_delta(GRID.lake.ice.K_domain_lb+1)./2;
    
    %residual heat flux used for ice cover
    GRID.lake.ice.dE_dt_cond_residual = dE_dt_cond_save - (dE_dt_cond(GRID.lake.ice.cT_domain_lb) + dE_dt_cond(GRID.lake.ice.cT_domain_lb+1));
end
